# MIT License
#
# Copyright (c) 2020 Joss Whittle
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


name: Update README

on:
  push:
    branches:
      - '**'
    paths:
      - README.md
      - README.template
      - .github/workflows/readme.yml

  workflow_dispatch:

env:
  JINJA_CMD: |
    import os, sys, jinja2
    github_releases = list(map((lambda tag: tag[len('refs/tags/'):]),
                           filter((lambda tag: tag.startswith('refs/tags/v')),
                           os.environ['GITHUB_TAGS'].split())))
    sys.stdout.write(jinja2.Template(sys.stdin.read()).render(env=os.environ, github_releases=github_releases))

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Install Jinja2
        run: pip3 install Jinja2

      - name: Add ENV variable for current branch
        run: |
          echo "GITHUB_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Add ENV variable for remote release tags
        run: |
          echo "GITHUB_TAGS=\"`git ls-remote --tags origin`\"" >> $GITHUB_ENV

      - name: Debug ENV
        run: |
          echo $GITHUB_BRANCH
          echo $GITHUB_TAGS

      - name: Execute Jinja2
        run: |
          cat README.template | python3 -c "${JINJA_CMD}" > README.md

      - name: Commit updated README and push to current branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: README.md
          commit_message: Regenerate README from template
