# MIT License
#
# Copyright (c) 2020 Joss Whittle
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


name: Build Singularity

on:
  workflow_dispatch:

jobs:
  build-singularity:
    name: Build Singularity
    runs-on: ubuntu-20.04

    steps:

      - name: Set branch name
        run: |
          echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set image names
        run: |
          echo "QUAY_IMAGE_NAME=quay.io/${{ secrets.QUAY_ORG }}/${{ secrets.QUAY_REPO }}:$IMAGE_TAG" >> $GITHUB_ENV
          echo "SYLABS_IMAGE_NAME=${{ secrets.SYLABS_ORG }}/${{ secrets.SYLABS_REPO }}/${{ secrets.SYLABS_REPO }}:$IMAGE_TAG" >> $GITHUB_ENV

      # Pull Docker image from Quay.io

      - name: Docker container build
        run: |
          docker pull $QUAY_IMAGE_NAME

      # Convert Docker image to Singularity image and push to Sylabs.io on success

      - name: Singularity container environment
        run: |
          docker pull quay.io/singularity/singularity:v3.9.4-slim
          docker run --name singularity_env -itd --entrypoint /bin/bash quay.io/singularity/singularity:v3.9.4-slim

      - name: Singularity container build
        run: |
          docker exec singularity_env singularity build ${{ secrets.SYLABS_REPO }}.sif docker://$QUAY_IMAGE_NAME

      - name: Singularity container push to Sylabs.io
        run: |
          echo "${{ secrets.SYLABS_TOKEN }}" > sylabs_token
          docker exec singularity_env singularity remote login --tokenfile sylabs_token
          docker exec singularity_env singularity push --allow-unsigned ${{ secrets.SYLABS_REPO }}.sif library://$SYLABS_IMAGE_NAME

      - name: Singularity container environment halt
        run: |
          docker stop singularity_env
          docker rm singularity_env
