import os
import random
import shutil
import unittest
import uuid
import mrcfile
import numpy as np

from pathlib import Path

# Test imports
import kompressor as kom

# This ensures all strings generated by uuid are repeatable.
random_generator = random.Random()
random_generator.seed(0)
X_AXIS = 5
Y_AXIS = 4
Z_AXIS = 3
unique_id = uuid.UUID(int=random_generator.getrandbits(128), version=4)
TEST_FOLDER = f"/tmp/kompressor_data_loader_test{unique_id}"


def delete_mrc_folder():
    if os.path.exists(TEST_FOLDER):
        shutil.rmtree(TEST_FOLDER)


class MRCDataloaderTests(unittest.TestCase):
    def setUp(self):
        delete_mrc_folder()
        os.mkdir(TEST_FOLDER)
        for i in range(1):
            with mrcfile.new(f"{TEST_FOLDER}/{i}.mrc") as mrc:
                mrc.set_data(
                    np.random.random(size=(X_AXIS, Y_AXIS, Z_AXIS)).astype(np.float32)
                )

    def tearDown(self):
        delete_mrc_folder()

    def test_mrc_data_loader(self):
        files = [TEST_FOLDER + "/0.mrc"]
        data_paths_and_frames = (
            kom.dataloaders.mrc_dataloader.get_data_paths_and_frames(files)
        )
        for frame in range(Z_AXIS):
            assert data_paths_and_frames[frame][0] == Path(files[0])
            assert data_paths_and_frames[frame][1] == frame

        with self.assertRaises(Exception) as context:
            kom.dataloaders.mrc_dataloader.get_data_paths_and_frames(["Non_File"])
        self.assertTrue("Non_File is not a file" in str(context.exception))

    def test_decode_mrc_data_path(self):
        files = [TEST_FOLDER + "/0.mrc"]
        data_paths_and_frames = (
            kom.dataloaders.mrc_dataloader.get_data_paths_and_frames(files)
        )
        for data_paths in data_paths_and_frames:
            data = kom.dataloaders.mrc_dataloader.decode_mrc_data_path(data_paths)
            assert data.shape == (X_AXIS, Y_AXIS, 1)
            assert data.dtype == np.float32
